### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AlexNova1555** [dotStart/Beacon#11]
**Describe the bug**
Stuck at Locating gate way

**To Reproduce**
1. open Beacon.exe
2 get stuck ON Locating gateway
3.?????
4. profit

**Expected behavior**
to work?

**Screenshots**
no need i hope

**Environment (please complete the following information):**
 - OS: Windows 10 version 2004
 - Application Version 2.4.0

**Additional context**
getting crash report
https://pastebin.com/nqxZsEXd

**Comment by dotStart** [comment]
This issue duplicates #10 which has been submitted via the error reporter sometime yesterday morning.

As it stands, this issue occurs when no compatible router is found within your network within the time limit of 5 Minutes (this timeout duration has since been lowered significantly). While I agree that it needs to be fixed (thus the existence of #10), it still means that your router most likely does not have the necessary prerequisites to work with Beacon (either UPnP has been disabled or the functionality simply isn't supported at all).

Going by the announcements in your log, you seem to be using the Tilgin HG2280 which does not seem to mention any support for port forwarding via UPnP in any of the documentation I could find. You may have some luck in the administration interface, however.
