### ISSUE TITLE
Gateway Error

### ISSUE THREAD

**Issue by PaulZappia** [dotStart/Beacon#4]
When I run the exe file, it starts up normally, then gets stuck on 'Waiting for Internet Gateway' and then shows a Gateway Error saying that my router doesn't support UPnP or that it is disabled. My router does have UPnP and it has always been on.
![gateway error](https://user-images.githubusercontent.com/45121450/67628997-529f6600-f8c3-11e9-99ff-b7b6a70797df.png)
What could I do to resolve this issue?
Thanks.

**Comment by dotStart** [comment]
Frankly, I can only see a hand full of options here. Only two of which you may be able to really do something about:

##### Windows Firewall
You may have cancelled or incorrectly confirmed the Windows firewall dialog without permitting access to your network (I noticed recently that Windows will sometimes display the dialog with the wrong settings checked leading to applications not getting the access since users do not understand the difference between the private / public / domain network check boxes).

You can check whether the application has access within the control panel (there's a part dedicated to the Firewall in the Security center thingy).

##### Gateway Control is disabled
Some routers have an additional toggle for internet gateway profile functionality (e.g. viewing the external address, NAT rules, etc) since they also include support for stuff like media servers. If this is the case, NAT control needs to be enabled at the very least for Beacon to detect the router as such and register routes (assuming the profile is implemented correctly; more on that below).

##### Slow Router
Potentially your router is incredibly slow in replying to UPnP announcements. This is pretty unlikely (yet may occur on cheap ISP models) due to the high timeout I've set on UPnP communication (at least for this particular startup step).

##### Non-Standard Network Topology
Sometimes home networks are configured differently from the typical `modem (or modem router combi) <-> computer` setup and this may lead to issues if there's additional routers or repeaters involved. You can only really fix this one by going for a more direct approach or finding a pair of routers that do not interfere here (in my tests this seems to work just fine with most non ISP routers).

##### Unsupported Router
While it may identify in the UI that it supports UPnP it may not properly implement the internet gateway profile (or not at all). In that case, there's not really anything to be done about this. While I could implement support for some uncompliant scenarios, I'm personally lacking access to an infinite warehouse of shitty routers so the compliance requirement will probably stick until I personally encounter a specimen in the wild.

**Comment by PaulZappia** [comment]
Thanks for the tips. I'll try to look into some of the things you mentioned and see which ones are causing my problem.
